name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore NuGet packages
        run: dotnet restore ./WeatherApi/WeatherApi.sln

      - name: Build .NET application
        run: dotnet build .\WeatherApi\WeatherApi.sln --configuration Release --no-restore
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build, tag, and push Docker image
        id: build-image
        run: |
          IMAGE_TAG=latest
          docker build -t weather-api:$IMAGE_TAG
          aws lightsail push-container-image --region eu-central-1 --service-name container-service-1 -label weather-api -- image my-webapi:$IMAGE_TAG
        env:
          AWS_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        
